import pandas as pd 
import re

def gpl_gse_title(df_general, df_gpl, df_gse):

    '''This function receives three dfs: the filtered df (Homo sapiens and ChiP-seq), gpl_title and gse_title. 
    It will return a df with the GPL_Title and GSE_Title'''

    df_gpl_nodup = df_gpl.drop_duplicates()
    df_gse_nodup = df_gse.drop_duplicates()

    df_1 = pd.merge(df_general, df_gpl_nodup, on='GPL')
    df_2 = pd.merge(df_1, df_gse_nodup, on='GSE')
    return df_2


def ctl_treat_class(df_2):
    
    '''Function to classify the GSM in control or treat samples and return a dataframe with this new column
    You should to pass a df as input containing the Title, Source_cell and Target columns. The columns will be parsed
    from a list of regex related to control and input terms'''

    list_categories = []
    df1 = df_2.copy()
    
    df1.fillna('None', inplace=True)
    
    
    patterns = [r"\bcontrol\b",r"\binput\b",r"[-_]?(input)[_-]?", r"[-_]?(Control)[_-]?", 
                r"\bctrl\b", r"[-_]?(ctrl)[_-]?", r"\bctl\b", r"[-_]?(ctl)[_-]?"]

    compiled_combined = re.compile('|'.join(x for x in patterns), re.IGNORECASE)


    #filtering using title, source-cell and target-antibody columns
    for index, row in df1.iterrows():
        if re.search(compiled_combined, row['Title']) or \
            re.search(compiled_combined, row['Source_cell']) or \
            re.search(compiled_combined, row['Target']):
            
            list_categories.append('Control')

        else:       
            list_categories.append('IP')

    df1["Categories"] = list_categories

    return df1


#load JF Dict 
def load_dict(file_name):

    '''function to generate a dictionary from a file with two strings separated by comma'''

    dict_target = {}

    target = open(file_name, 'r')

    for i in target:
        i = i.strip()
        key,value = i.split(',')
        dict_target[key]=value

    return dict_target


#Creating a list of target from dict_target
def list_regex_values(dict_target):

    '''This function will return a string with all values (targets-regex) from a dictionary. It will return a list of all regex to be used by
    the next function'''

    all_regex = dict_target.values()

    all_regex_str = "|".join(all_regex)

    all_regex_compiled = re.compile(all_regex_str,re.IGNORECASE)
    
    return all_regex_compiled


def target_CL(df_ctl_IP, file_name):
    
    '''This function receives the main df (df_ctl_IP) and all_regex_compiled. The code will a target in all_regex_compiled 
    (generated by list_regex_values function) doing a parse in 3 columns, and classify the confidence intervals according with 
    the column that the target was found. You shoud give a df containing a Source_cell, Title and Target columnn'''
    
    all_regex_compiled = list_regex_values(load_dict(file_name)) 
    gsm = df_ctl_IP['GSM'].tolist()
    length = len(df_ctl_IP.index)
    
    #put the df_lengh for range
    list_target = list(range(length))

    #put the df_lengh for range
    CL = list(range(length))

    for index, row in df_ctl_IP.iterrows():
        match_source  = re.search(all_regex_compiled, row["Source_cell"])
        match_title  = re.search(all_regex_compiled, row['Title'])
        match_target  = re.search(all_regex_compiled, row['Target'])


        if match_source:
            list_target[index] = match_source.group()
            CL[index] = 'third'

        if match_title:
            list_target[index] = match_title.group()
            CL[index] = 'second'

        if match_target:
            list_target[index] = match_target.group()
            CL[index] = 'first'
        
        if isinstance(CL[index], int):
            CL[index] = gsm[index]
            list_target[index] = gsm[index]
              
    return list_target, CL


def columns_target_CL(df_ctl_IP, list1, list2):

    '''This function receives to list and will create new columns to return a df'''

    df1 = df_ctl_IP.copy()
    
    df1['Target-interest'] = list1
    df1['CL-target'] = list2
    
    return df1


def correct_target(df, column, target):
    
    '''Receives a df (df_almost), a string (column to be filled, i.e: Categories) and another string (target name).
    Returns a df'''
    
    control_df = df[df['Categories'].str.contains('Control')]

    index_control = control_df.index.values.tolist()

    for index in index_control:
        
        df.at[index, column] = target
        
    return df


def reorder_cols(df_almost_target_index):

    '''This function receives the df (including GPL and GSE title, target-interest and CL) columns to reorder them.
    It will return a df with the Title column renamed to GSM_Title and the reordered columns'''

    df_almost_target_index.rename(columns={'Title':'GSM_title'}, inplace=True)
   
    cols_new = ['Release-Date', 'Organism', 'Library_strategy', 'GPL','GPL_title', 'GSE', 'GSE_title', 'GSM','GSM_title', 'chip_antib_catalog', 'Target', 'Cell_line', 'Cell_type', 'Source_cell', 'Categories', 'Target-interest', 'CL-target']
    df= df_almost_target_index[cols_new]

    return df


def add_srr_count_col(df_col_reorder, df_gsm_adr_srx_srr_final):

    df1 = df_gsm_adr_srx_srr_final[['GSM', 'SRR_Count']].copy()
    df_final = pd.merge(df_col_reorder, df1, on='GSM')
    return df_final





