import pandas as pd 
import re
import sys



def fill_na(df_2):
    '''This function receives a df 
    and return a copy with blank cells 
    filled with ----'''

    df1 = df_2.copy()
    df1.replace('', '----', inplace=True)

    return df1


#load JF Dict 
def load_dict(file_name):
    '''function to generate a 
    dictionary from a file with 
    two strings separated by comma'''

    dict_target = {}

    target = open(file_name, 'r')

    for i in target:
        i = i.strip()
        key,value = i.split(',')
        dict_target[key]=value

    return dict_target


#Creating a list of target from dict_target
def list_regex_values(dict_target):
    '''This function will return a string 
    with all values (targets-regex) from a 
    dictionary. It will return a list of all 
    regex to be used by
    the next function'''

    all_regex = dict_target.values()
    all_regex_str = "|".join(all_regex)
    all_regex_compiled = re.compile(all_regex_str,re.IGNORECASE)
    
    return all_regex_compiled



def columns_target_CL(df_ctl_IP, list_target, CL, list_target_target, list_target_catalog):
    '''This function receives two list and will 
    create new columns to return a df'''

    df1 = df_ctl_IP.copy()
    df1['Target-interest'] = list_target
    df1['CL-target'] = CL
    df1['Target-target'] = list_target_target
    df1['Target-catalog'] = list_target_catalog
    
    return df1


def target_CL(df_ctl_IP, all_regex_compiled):
    '''This function receives the main df 
    (df_ctl_IP) and all_regex_compiled. The 
    code will a target in all_regex_compiled 
    (generated by list_regex_values function) 
    doing a parse in 3 columns, and classify the 
    confidence intervals according with the column
    that the target was found. You shoud give a df 
    containing a Source_cell, Title and Target columnn'''
     
    gsm = df_ctl_IP['GSM'].tolist()
    length = len(gsm)
    # print(f'length_gsm_list:{length}')
    
    #put the df_length for range #create two more columns (Target_target and Target_catalog)
    list_target = list(range(length))
    list_target_target = list(range(length))
    list_target_catalog = list(range(length))

    #put the df_length for range
    CL = list(range(length))

    index = 0
    for lindex, row in df_ctl_IP.iterrows():
        match_source  = re.search(all_regex_compiled, row["Source"]) #updating col names
        match_title  = re.search(all_regex_compiled, row['GSM_title'])
        match_chip_ant  = re.search(all_regex_compiled, row['ChIP-antibody-catalog'])
        match_target  = re.search(all_regex_compiled, row['Target'])

        if match_source:
            list_target[index] = match_source.group()
            CL[index] = 'fifth'

        if match_title:
            # print(f'last index tried: {index}')
            list_target[index] = match_title.group()
            CL[index] = 'fourth'

        if match_target:
            list_target[index] = match_target.group()
            # print(row['GSM'])
            # print('target',list_target[index])
            CL[index] = 'third'

        if match_chip_ant:
            list_target[index] = match_chip_ant.group()
            # print(row['GSM'])
            # print('antibody',list_target[index])
            CL[index] = 'second'        
        
        if match_target and match_chip_ant: 
            list_target[index] = match_target.group() + ':::' + match_chip_ant.group() #fixed!
            list_target_target[index] =  match_target.group()
            list_target_catalog[index] =  match_chip_ant.group()
            # print(row['GSM'])
            # print('target',list_target[index])
            CL[index] = 'first'
        else:
            list_target_target[index] =  '----'
            list_target_catalog[index] =  '----'

        if isinstance(CL[index], int):
            CL[index] = gsm[index]
            list_target[index] = gsm[index]

        index += 1
              
    # columns_target_CL(df_ctl_IP, list_target, CL, list_target_target, list_target_catalog)
    return columns_target_CL(df_ctl_IP, list_target, CL, list_target_target, list_target_catalog)


def reorder_cols(df_almost_target_index):
    '''Receives a df including GPL and GSE title
    ,target-interest and CL columns. Return a df
    with reordered columns'''

    #no categories
    cols_new = ['Release-date', 'Library-strategy','Organism', 
                'GPL', 'GPL-title', 'GSE','GSE-title', 'GSM','GSM_title',
                'Cell', 'Disease', 'Sex_GEO','Source','ChIP-antibody-catalog',
                'Target', 'Target-interest', 'Target-target','Target-catalog','CL-target',
                ]
    
    return df_almost_target_index[cols_new]


def add_srr_count_col(df_col_reorder, df_gsm_adr_srx_srr_final):
    '''This function receives two dfs and returns a df_final with 
    the re-ordered columns'''

    df1 = df_gsm_adr_srx_srr_final.copy()

    return df_col_reorder.merge(df1, how='left', on='GSM')    





